### ISSUE TITLE
Format whole thing

### ISSUE THREAD

**Issue by themandalore** [charonAMM/js_ui#4]
Let's make it pretty

**Comment by themandalore** [comment]
just running issue list: 
 - remove copyright thing
 -  just have "charon" at top
did you change the set up instructions?  I did a git pull, npm i, npm start and it looks nothing like yours

**Comment by markdeveloper2023** [comment]
@themandalore I have removed copyright in the footer via this pull request https://github.com/charonAMM/js_ui/pull/8
I didn't change the set up instructions. I only changed HTML and added css code in pages and modals folders.

**Comment by themandalore** [comment]
Awesome works great now 
New notes:
- remove whole footer (github and title)
-  allow switching of dropdown and CHD in trade menu
- change everything to lower case (no capital letters anywhere, just a design thing)
- clicking out of home screen then back on breaks it

**Comment by markdeveloper2023** [comment]
@themandalore  Thanks for your feedback. I am improving it following your guidance and will make a pull request soon!

**Comment by markdeveloper2023** [comment]
Hi @themandalore,
I open a pull request #10 for solving 2 issues including remove whole footer & change everything to lower case. Could you explain more about "allow switching of dropdown and CHD in trade menu", so I can implement it more correctly?

In addition, I guess the issue of clicking out of home screen then back on breaks it came from backend code of project (JS code or electron) as I also faced this issue in the first time when implementing this project and tested html site independently and it works normally. I am investigating these backend code.

**Comment by markdeveloper2023** [comment]
@themandalore I haven't hooked up any backend yet. I will try it. Also, make a pull request for switching.

**Comment by themandalore** [comment]
Any chance for the switching you can just add a button in the middle (or side ) like:  https://app.uniswap.org/#/swap?  
And on the trade screen, for some reason a scroll bar doesn't pop up for me to move it down
